# Generated by Django 2.2.4 on 2019-08-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-active', 'order', 'name')},
        ),
        migrations.RemoveField(
            model_name='message',
            name='mailing_list',
        ),
        migrations.AddField(
            model_name='message',
            name='mailing_list',
            field=models.ManyToManyField(to='news.MailingList'),
        ),
    ]
