# Generated by Django 2.2.4 on 2019-08-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190807_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mailing_list',
            new_name='mailing_lists',
        ),
        migrations.RemoveField(
            model_name='message',
            name='first_newsletter',
        ),
        migrations.RemoveField(
            model_name='message',
            name='last_newsletter',
        ),
    ]
