# Generated by Django 2.2.4 on 2019-08-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190807_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='send_frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='D', max_length=1, verbose_name='Send frequency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='send_reminder',
            field=models.BooleanField(default=False, verbose_name='Send events reminders'),
        ),
    ]
