# Generated by Django 2.2.4 on 2019-08-07 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190807_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='reminder_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_mailinglist', to='news.Template'),
        ),
    ]
