# Generated by Django 2.2.4 on 2019-08-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_mailinglist_reminder_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='subject',
            field=models.CharField(default='', max_length=255, verbose_name='Email subject'),
            preserve_default=False,
        ),
    ]
